### ISSUE TITLE
Being told I'm not entitled to entitlements for BF3 despite owning premium

### ISSUE THREAD

**Issue by Simber1** [Imposter/otool#2] opened 2020-10-13 02:02 UTC
As the title says I get told "This account is not entitled to OFB-EAST:55172" despite owning BF3 Premium and Limited edition.

**Comment by Imposter** [comment] 2020-10-13 18:51
Caused by lack of correct documentation. This is only caused due to using the example commands and not updating the IDs to reflect your entitlements. BF3 Premium has different DLC entitlement IDs when compared to BF3 Standard. Please see new documentation.

Fixed in 54d3da5c621ab8932c7059d49e2e3ec366bcee78.

**Closed by Imposter** 2020-10-13 18:51 UTC
Labels: documentation
